require('_keymap')
require('_configuration')
require('_packer')
require('_options')
require('_lsp')
require('_git')
require('_lualine')
require('_bufferline')
require('_formatter')
require('_dap')
require('_telescope')
require('_treesitter')

require('Comment').setup()
require('go').setup()
require('mason').setup()
require('mini.files').setup()

